#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAp79KVgy5/M1Q2b0y92XyhhceAUAQsoN5Ukf7zwQwhmeSp4+J
    rk2MFRcKmkEXevSxhPN8DCse1Lo3w82BGosayCfRGi9KzaGrtgHFgwk1rncCXpRA
    BD2xqYYmrmMxRI4TPrnD8z00JiS8LodQkKt58yrxs2yYpJpK0iUDWF5vLnuhO68D
    t6wjfBVgA1u6Zh6HB4FY5TxPnJu36OLelZ5tzAAleWfJ9DqamdsVv0b6asBvWlMF
    GPI+zpaSDpr3dR00WIqxUQuFrmg9PQNXViK73tHuvrb+0alwvOV2HggfrE4qQg3J
    L5VA6Td+hTdrGxooJhncWtsxuLsmGjiEgipZSQIDAQABAoIBAFQQdiVXbWF2Vx03
    RrJawcZXEW9Y9sUvQ/5rGpMtK1A/2Wvlb/8M17W9/U8+bZDtzYSuLK1Acsvyon2a
    oCd4LKy/33d62cbhTVcB3kSDugY7l9FkBAzcCgvFsd7U0NzlQlm96KgeNOMkp7W9
    lC9b79pf3A6pznk25WYYrGt9r8Qf2sPVOZBqwh3+iESNrxIbeGUf6ihfTJH4TSuy
    jcQzV7x8avOoxTh3ERGZOOGTLEVX8pAWsYZRSFhbRN14G0e9LyyFzJR8TerD/Kuk
    B6YClnfMsPZtlCqrbANX7j3SHG+VSM2/tpyXWV926OXAp9h8a3uku0iSbJ2/wo4O
    y34tuq0CgYEA2YnIDAEH3JnFAnaNulAWl07zWxi8hUwfl3aC/S9i1B09/7E/9NJp
    0319DnNw6yYSSrxF2sf7RJi6B1ZggRKhdpUbweDQhkuMYvr1ZRwSkCPMpIXbv4fi
    PzGD+m0yQGBG/b9yLm8kYoM/ZrrS+51HTUgq24K1cX/L1SQRrZ/j43MCgYEAxWfe
    XfVy1MmpgsrPw83FMdKiF3TkNZcXA2ljsjxb6t+HQ2ikWmlAWKu/b0NS8Ge7Kywj
    Zg/vd0lL7QMonVf2+brh/9AREyUkNP2iooauzdNEw4GNkZ0LOlC1+QPmfwsJ0DCi
    me5QEbBJ+xXjGBTB4t8d4YXkiA9+2EE+JCEROVMCgYEAs5rjVK3hLMy0cOUq/OG0
    1TY1DEhvFesUxjvtyFZAVXrTPnG8qUi0YQ3hm3XKjAtB3Px2/DxSg39JUFeLk+Wq
    87oGUdtorwhfHzWuN82mseUsx8VQ+mCZdq1OFwvjCm2zDzvqbNYMh11vkkS7f0yK
    mw7ze4r+fXgS9aYzBlPVlmsCgYAj4vAP0LEhcc+5ETmX9O5mUk5ZSUy7WU47tosD
    OenT1vL2FC3cqcmi1QYmKe0H+zORc6KzyS3VV6PP4IUfpYAmggzXvnF8M4JTh9Br
    D2Tz0fZsPD8KO6xw239ZV5Ytfko4aL8GkMZJkOzCEoaIOC3PGpSKDRcwjPCYS7QK
    SWCiNQKBgQCQXRQNAVLgX+S83JtMvs1+3KeB6uPg3QxW8b4abh9cIHQUj9EcdRH7
    hA+f7x6RbffUdwO9hk36GLmZjtzz86LW1jJD3xlB+StuBKY2DNIBQQfGzk4tBKCa
    45G3wK6x3ht36gYEjWxf3EqWLTZFA5L/llYulPZYfkXysY1V9xopfw==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/ccbprep_release.key
      iv_filename:  /etc/rails/keys/ccbprep_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEA2unHO2beDwTAMObKCi2FUo9BpcUuFZ11dxWnoAVvjBpv1Fyv
    DtVcP2RyZn0LBJqDG+e9XFkDK10ctJh8CF1T7ohFnIEeWbeXXEErNDPAx8fr8H91
    1KL8viu80jSamidvj9fXr1ghGg93fux4TSPmyYSLoXR+OOO7Uo4FdUuMMaIbKflq
    lYTZGBz8x2ONu3upN9cSPB3x3i9zmE0TRHcLBpCh883H15+dMmVPkzOtfNAo7HNJ
    n0OB83Jp1P1I73JxIyyDvlcUXIKV0ivryjQX5BiBGutNBkSIunhrBncpwJNx9YF0
    j7Wb6/vU0gh+Ac4eAe1M69krWfFkklWQDW5nxwIDAQABAoIBAGxz7TRMni6ql9yi
    Oe4Y5zgjqM5Lha1HuO4qWEU67Cxo3IZE9KVQpsbxKIwF3vOE6PdmM7YQkzVkh9gg
    wzIRqoc+E96ZSUQBZIdb8d+G1DcloIohW2rg5H4ChSVO0lkUuHx23nAMJToX94d1
    95Of+bJUbCis4eulRyR7H9EggHAFiLAfnE0jULTF9c8IHoEpcw0WL9HXATlDkf7Z
    x+06hOFHiOm+A4yGx80cFz1he3mLgmQuM8bwfMNsoQ+yTAgaMSk0MBO7Yo+byrrV
    fdBrlp1/kwXtuxEvdZF5xKG/L/c1D8/mX88Ig0ZACr53WsK1rqz6PGk/ZvnApd40
    v2+Y1iECgYEA+dQzLmbUY2NILE1lkTOf82u5I5cQn57VHXMEt9CQ3n1Om4oYuqfL
    9lIFrCsgTE95NDvyTj2nbg+jEguVw1nFZ2hd/0vKrGVgZoxXW2w10zTCqyxk2jzY
    lo1Frsvg5pgmd6RQzBo/AtnI0ZcpymK51Tj0FKekQUPiycDH8cBh8NsCgYEA4FIU
    ++aIG3EYunx370Y5+k+frOrzf5kbG27VL/f2z08pB3GRn5HUsKeClJpv+HnkaFgw
    z5ChwcuTwyxw7ClKkGeo8dMPrw/HPXHLKQf53Eh4XdICGpzunvA9MIQa7q2jIzcf
    MBiMLwwuRiKpxRvwCQ5J2nlp/gqET3MzPzV8soUCgYBCLEnOPaB+HtsMGQgRGNqC
    MINegPH/RaPvY/rY8V6eABTlMAPy1OU6fmlQPDAW5moVQtegj8Ycafnomrb1gn6+
    MC/NonaxiTyqjPvKlHQBWJVDn8Oq5rj7z7moXgpZKe3ufNCF72HHUIZXtbF1EQdm
    Cerk2a6xNtkIVY7gYvPORwKBgBsoFL5CNGwODw5Ujzh6af5xsUT/1Ka35F431rtN
    66VBUhhCmXyV7QfN37MZ10BfkVVIh/A49Dw/5w2Tzb/pZ8t/oSZVhOqOoHJB2nSH
    MKqIY3oIOJT8Nq8rKl07QP9wKfXTcIUkE6SGdvuqqp7gOPj/r9UxKbHFmCr+KVAX
    q5b5AoGAM21fImqys5HoMt40bKXcv0BbVg9WipITeKLLvfawULtpFkRi/CP/v8N2
    ZDLVAXNwxXTCmbkkpw5HEcO7JUtEEFpHr3F0R6z0ExvfG2h4CKhhO0tjkdZQZe1/
    0aRawkqztmqHZeofMM3Ufyc4YtReZ5qSUzGf9RfPNgECvdgNDoM=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/ccbprep_production.key
      iv_filename:  /etc/rails/keys/ccbprep_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
